---
name: check_outputs

'on':
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

jobs:
  check_outputs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: run check_all
        run: |
          ./check_all.sh
...
